name: Java CI with JShell

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Compile Java
      run: javac src/HelloWorld.java

    - name: Run Java Program
      run: java -cp src HelloWorld

    - name: Run JShell Script
      run: jshell script.jsh
